### ISSUE TITLE
Tiptac and TRP issue.

### ISSUE THREAD

**Issue by Aerithissa** [Ellypse/Total-RP-3-Extended#141] opened 2018-08-02 19:40 UTC
I've narrowed this down to TRP and Tiptac.

https://imgur.com/a/PKk42Ax

This is what happens (Glossy white bar near the lantern)

Is there a way to fix this, I had to disable Tiptac, since TRP is vital to me.

**Comment by Solanya** [comment] 2018-08-02 19:41
Wrong repository + duplicate of https://github.com/Ellypse/Total-RP-3/issues/182

**Closed by Solanya** 2018-08-02 19:41 UTC
